name: AssignReviewers

on:
  pull_request

jobs:
  add-reviewer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ohnogumi/assign-reviewers@v0.0.5
        with:
         # required
         # If you assign team for reviewer, you generate a personal access tokens with workflow scope. 
         token: "${{ secrets.GITHUB_TOKEN }}" # "${{ secrets.PERSONAL_TOKEN }}"

         # optional 
         config: "REVIEWERS"
